services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434'
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=${database}'
      - 'POSTGRES_PASSWORD=${password}'
      - 'POSTGRES_USER=${username}'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
